CREATE TABLE ENERGY_PRICES(
  ENERGY_PRICES_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  QUARTER VARCHAR(16) NOT NULL,
  MINING_SHAPE DECIMAL NOT NULL,
  INDUSTRIAL_SHAPE DECIMAL NOT NULL,
  COMMERCIAL_SHAPE DECIMAL NOT NULL,
  ENERGY_PRICE DECIMAL NOT NULL,
  LGC_PRICE DECIMAL NOT NULL
);